spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/instagram
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret-key: secret
  validity-in-hours: 24